Repository simplifiedautomation/simplified-ui, pull requests merged in 2020-10, with the labels that each got.

#5 Update readme to start contributions
  README.md
  images/table.gif
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#7 Add headless karma testing and run on PRs
  .github/workflows/test.yml
  package-lock.json
  package.json
  projects/simplified-ui/src/lib/models/SaButton.ts
  src/karma.conf.js
Labels: enhancement, hacktoberfest-accepted

#8 Create build.yml
  .github/workflows/build.yml
Labels: enhancement, hacktoberfest-accepted

#9 removed action on master push
  .github/workflows/build.yml
Labels: bug, hacktoberfest-accepted

#10 Publish GitHub Action
  .github/workflows/build.yml
  .github/workflows/publish.yml
Labels: enhancement, hacktoberfest-accepted
